from typing import Any

class Pin:
    IN: int
    OUT: int
    def __init__(self, id: int, *args: Any, **kwargs: Any) -> None: ...

class SPI:
    def __init__(self, id: int, *args: Any, **kwargs: Any) -> None: ...

class Timer:
    ONE_SHOT: int
    def __init__(self, id: int) -> None: ...
    def init(self, *, period: int, mode: int, callback: Any) -> None: ...

class WDT:
    def __init__(self, *, timeout: int) -> None: ...
    def feed(self) -> None: ...

def reset() -> None: ...
def reset_cause() -> int: ...
