from typing import Any

PHY_W5500: int
ETH_INITIALIZED: int
ETH_STARTED: int
ETH_STOPPED: int
ETH_CONNECTED: int
ETH_DISCONNECTED: int
ETH_GOT_IP: int

class LAN:
    def __init__(self, **kwargs: Any) -> None: ...
    def active(self, value: bool | None = None) -> bool: ...
    def status(self) -> int: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self, value: Any = None) -> Any: ...
    def ipconfig(self, *args: Any, **kwargs: Any) -> Any: ...
